# Generated by Django 4.1.3 on 2022-12-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address_alter_user_gst_number_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VEG', 'Veg'), ('NONVEG', 'Non-Veg'), ('EGG', 'Eggitarian')], max_length=10)),
                ('thumbnail', models.ImageField(upload_to='dishes_thumbnail/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.AddField(
            model_name='dishe',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of', to='restaurant.restaurant'),
        ),
    ]
