# Generated by Django 4.1.3 on 2022-12-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dishe_delete_dishes_rename_restaurants_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishe',
            new_name='Dish',
        ),
    ]
