# Generated by Django 4.1.3 on 2022-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='base_price',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
