# Generated by Django 4.1.3 on 2022-12-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_buyers_delete_vendors_buyer_vendor'),
        ('restaurant', '0007_dish_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restra_rating', to='accounts.buyer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_rating', to='accounts.buyer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='restaurant.dish')),
            ],
        ),
    ]
